#!/usr/bin/python3
# Used to check cameras before committing to install
# Executed before primary apt install of files

import subprocess
import sys
import os

# Backup the config file if we're upgrading
if "upgrade" in sys.argv:
	# Try to copy the config file as a backup
	try:
		# Try to copy the new location first
		if os.path.exists("/etc/ubuntu-hello/config.ini"):
			subprocess.call(["cp /etc/ubuntu-hello/config.ini /tmp/ubuntu_hello_config_backup_v" + sys.argv[2] + ".ini"], shell=True)
		# If that does not exist, try copying the old location
		else:
			subprocess.call(["cp /lib/security/ubuntu-hello/config.ini /tmp/ubuntu_hello_config_backup_v" + sys.argv[2] + ".ini"], shell=True)

		# Let the user know so he knows where to look on a failed install
		print("Backup of Ubuntu Hello config file created in /tmp/ubuntu_hello_config_backup_v" + sys.argv[2] + ".ini")
	except subprocess.CalledProcessError:
		print("Could not make an backup of old Ubuntu Hello config file")

	# Don't continue setup when we're just upgrading
	sys.exit(0)

# Don't run if we're not trying to install fresh
if "install" not in sys.argv:
	sys.exit(0)
