# Python sources
usr/lib/*/ubuntu-hello-gtk/

# Desktop file
usr/share/applications/ubuntu-hello-gtk.desktop

# Icons (legacy pixmap + hicolor vector/symbolic)
usr/share/pixmaps/ubuntu-hello-gtk.png
usr/share/icons/hicolor/scalable/apps/ubuntu-hello-gtk.svg
usr/share/icons/hicolor/symbolic/apps/ubuntu-hello-gtk-symbolic.svg

# Data files (glade, logos)
usr/share/ubuntu-hello-gtk/

# Gettext message catalogs
usr/share/locale/*/LC_MESSAGES/ubuntu-hello-gtk.mo

# Polkit policy
usr/share/polkit-1/

# GTK binary
usr/bin/ubuntu-hello-gtk
