# Python sources
usr/lib/*/ubuntu-hello-gtk/

# Desktop file
usr/share/applications/ubuntu-hello-gtk.desktop

# Icon
usr/share/pixmaps/ubuntu-hello-gtk.png

# Data files (glade, logos)
usr/share/ubuntu-hello-gtk/

# Gettext message catalogs
usr/share/locale/*/LC_MESSAGES/ubuntu-hello-gtk.mo

# Polkit policy
usr/share/polkit-1/actions/com.github.ventura8.ubuntu-hello-gtk.policy

# GTK binary
usr/bin/ubuntu-hello-gtk
