# PAM module
usr/lib/*/security/pam_ubuntu_hello.so

# Python sources
usr/lib/*/ubuntu-hello/

# CLI binary
usr/bin/ubuntu-hello

# Configuration template (live config under /etc is created by package-configure)
etc/ubuntu-hello/

# Bash completion
usr/share/bash-completion/completions/ubuntu-hello

# PAM config
usr/share/pam-configs/ubuntu-hello
etc/pam.d/ubuntu-hello-verify

# Man page
usr/share/man/man1/ubuntu-hello.1

# Data files
usr/share/ubuntu-hello/

# Gettext message catalogs
usr/share/locale/*/LC_MESSAGES/ubuntu-hello.mo
